apiVersion: v1
kind: Secret
metadata:
  name: wireguard
  namespace: wireguard
type: Opaque
stringData:
  wg0.conf.template: |
    [Interface]
    Address = 100.64.0.0/10
    ListenPort = 51820
    PrivateKey = cKINQP+ubnDnkI48KQnpcfDJN1E37Q4gVShYpGjuVXw=
    PostUp = iptables -A FORWARD -i ENI -j ACCEPT; iptables -A FORWARD -o ENI -j ACCEPT; iptables -t nat -A POSTROUTING -o ENI -j MASQUERADE
    PostUp = sysctl -w -q net.ipv4.ip_forward=1
    PostDown = iptables -D FORWARD -i ENI -j ACCEPT; iptables -D FORWARD -o ENI -j ACCEPT; iptables -t nat -D POSTROUTING -o ENI -j MASQUERADE
    PostDown = sysctl -w -q net.ipv4.ip_forward=0

    [Peer]
    # Example Peer 1
    PublicKey = fLpzLGIYjtJ/fed+GyWktF4/VSE6ov7JQXqYyKCfTTA=
    AllowedIPs = 100.64.0.4/32