apiVersion: v1
kind: Service
metadata:
  name: wireguard
  namespace: kube-system
spec:
  ports:
  - port: 51820
    protocol: TCP
    targetPort: 51820
  selector:
    name: wireguard
  type: LoadBalancer
